
#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#

name: RAX3000Me

on:
  push:
    branches:
      - main
    paths:
      - 'RAX3000Me/.config'
  workflow_dispatch:
  schedule:
    - cron: '0 4 1 * *'

env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt.git
  REPO_BRANCH: openwrt-24.10
  TOOLCHAIN_TAG: immortalwrt-toolchain
  TOOLCHAIN_CACHE: false
  UPLOAD_FIRMWARE: false
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Ê£ÄÊü•È°πÁõÆÂàÜÊîØ
      uses: actions/checkout@main

    - name: ÂàùÂßãÂåñÁºñËØëÁéØÂ¢É
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo apt update
        sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.org/init_build_environment.sh)'
        sudo apt autoremove --purge
        sudo apt clean
        sudo timedatectl set-timezone "$TZ"
        sudo chown $USER:$GROUPS /mnt
        echo "FIRMWARE_VERSION=$(date +"%y%m%d")" >> $GITHUB_ENV
        echo "START_DATE=$(date +%s)" >> $GITHUB_ENV

    - name: ‰∏ãËΩΩÊ∫êÁ†Å
      working-directory: /mnt
      run: |
        df -hT $PWD
        git clone --single-branch --depth 1 -b $REPO_BRANCH $REPO_URL openwrt
        REPO_NAME="$(echo $REPO_URL | awk -F '/' '{print $(NF-1)}')"
        echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
        cd openwrt
        echo "openwrt_root=$PWD" >> $GITHUB_ENV

    - name: Âä†ËΩΩËΩØ‰ª∂Ê∫ê
      env:
        FEEDS_CONF: ${{ github.workflow }}/feeds.conf.default
        DIY_P1_SH: ${{ github.workflow }}/diy1.sh
      run: |
        [ -e $FEEDS_CONF ] && mv $FEEDS_CONF $openwrt_root/feeds.conf.default
        chmod +x $DIY_P1_SH
        cd $openwrt_root
        $GITHUB_WORKSPACE/$DIY_P1_SH

    - name: Êõ¥Êñ∞Âπ∂ÂÆâË£ÖËΩØ‰ª∂Ê∫ê
      run: cd $openwrt_root && ./scripts/feeds update -a && ./scripts/feeds install -a

    - name: Âä†ËΩΩËá™ÂÆö‰πâÈÖçÁΩÆ
      env:
        CONFIG_FILES: ${{ github.workflow }}/files
        CONFIG_FILE: ${{ github.workflow }}/.config
        DIY_P2_SH: ${{ github.workflow }}/diy2.sh
      run: |
        [ -e $CONFIG_FILES ] && mv $CONFIG_FILES $openwrt_root/files
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE $openwrt_root/.config
        chmod +x $DIY_P2_SH
        cd $openwrt_root
        $GITHUB_WORKSPACE/$DIY_P2_SH
        TARGET=$(grep "CONFIG_TARGET_[^_]*_[^_]*=y" .config | sed "s/^CONFIG_TARGET_\([^_]*_[^_]*\)=y/\1/g")
        echo "TARGET=$TARGET" >> $GITHUB_ENV
        TARGET_PATH=$(echo $TARGET | sed 's/_/\//g')
        if [ $TOOLCHAIN_CACHE == 'false' ]; then
          wget -O llvm-bpf.tar.zst https://downloads.immortalwrt.org/releases/24.10-SNAPSHOT/targets/$TARGET_PATH/llvm-bpf-18.1.7.Linux-x86_64.tar.zst
          tar -xaf llvm-bpf.tar.zst
        fi

    - name: ‰∏ãËΩΩÂåÖ
      id: package
      run: |
        cd $openwrt_root
        make defconfig
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: ÂáÜÂ§áÁºìÂ≠òÁöÑ Toolchain
      id: toolchain
      continue-on-error: true
      if: env.TOOLCHAIN_CACHE == 'true'
      run: |
        cd $openwrt_root
        export CURRENT_HASH=$(git log --pretty=tformat:"%h" -n1 tools toolchain)
        echo "CURRENT_HASH is $CURRENT_HASH"
        export CACHE_HASH=$(curl -fSsL https://github.com/$GITHUB_REPOSITORY/releases/download/$TOOLCHAIN_TAG/cache-hash.txt)
        echo "CACHE_HASH is $CACHE_HASH"
        if [ "$CURRENT_HASH" == "$CACHE_HASH" ]; then
          wget -qc https://github.com/$GITHUB_REPOSITORY/releases/download/$TOOLCHAIN_TAG/$REPO_NAME-$REPO_BRANCH-$TARGET.tar.xz -O - | tar -xJ
          sed -i 's/ $(tool.*\/stamp-compile)//;' Makefile
        fi

    - name: ÁºñËØëÂõ∫‰ª∂
      id: compile
      run: |
        cd $openwrt_root
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 V=s
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Êï¥ÁêÜÊñá‰ª∂
      id: organize
      if: steps.compile.outputs.status == 'success' && !cancelled()
      run: |
        # Êï¥ÁêÜÂõ∫‰ª∂ÂåÖÊó∂ÂÄô,Âà†Èô§ÊÇ®‰∏çÊÉ≥Ë¶ÅÁöÑÂõ∫‰ª∂ÊàñËÄÖÊñá‰ª∂,ËÆ©ÂÆÉ‰∏çÈúÄË¶Å‰∏ä‰º†Âà∞ActionsÁ©∫Èó¥
        cd $openwrt_root/bin/targets/*/*
        mkdir -p package
        mv packages package/core
        mv package packages
        mv $openwrt_root/bin/packages/*/* packages
        tar -czf packages.tar.gz packages
        rm -rf packages
        mv *sysupgrade.itb ${{ github.workflow }}-250326-squashfs-sysupgrade.itb
        rm -rf version.buildinfo
        rm -rf profiles.json
        rm -rf feeds.buildinfo
        rm -rf sha256sums
        rm -rf *bl2.bin
        rm -rf immortalwrt*
        echo -e "$(sha256sum *)\n" > sha256sums
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT

    - name: ‰∏ä‰º†Âõ∫‰ª∂Âà∞Github ActionsÁ©∫Èó¥
      if: steps.organize.outputs.status == 'success' && env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      uses: actions/upload-artifact@main
      with:
        name: ${{ github.workflow }}-${{ env.FIRMWARE_VERSION }}
        path: ${{ env.FIRMWARE }}

    - name: Âà†Èô§ÊóßÁöÑRelease
      if: steps.organize.outputs.status == 'success' && env.UPLOAD_RELEASE == 'true' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG_NAME: ${{ github.workflow }}
      run: |
        git push origin --delete ${{env.TAG_NAME}} || echo "ËøúÁ®ãÊ†áÁ≠æ‰∏çÂ≠òÂú®"
        RELEASE_URL="https://api.github.com/repos/${{ github.repository }}/releases/tags/$TAG_NAME"
        RELEASE_ID=$(curl -s -H "Authorization: token $GITHUB_TOKEN" $RELEASE_URL | jq -r '.id')
        if [ "$RELEASE_ID" != "null" ]; then
          echo "üóëÔ∏è Âà†Èô§Release‰∏≠: $RELEASE_ID..."
          curl -X DELETE -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/${{ github.repository }}/releases/$RELEASE_ID"
          echo "‚úÖ ReleaseÂà†Èô§ÊàêÂäü!"
        else
          echo "‚ö†Ô∏è Êú™ÊâæÂà∞tagÁöÑRelease: $TAG_NAME"
        fi

    - name: ÂàõÂª∫releaseÊ†áÁ≠æ
      id: tag
      if: steps.organize.outputs.status == 'success' && env.UPLOAD_RELEASE == 'true' && !cancelled()
      run: |
        echo "ÁºñËØëÊó∂Èó¥Ôºö$(date -d "@${{ env.START_DATE }}" +"%YÂπ¥%mÊúà%dÊó• %HÁÇπ%MÂàÜ")" >> release.txt
        echo "ÈªòËÆ§ÁΩëÂÖ≥Ôºö192.168.5.1" >> release.txt
        echo ÂåÖÂê´Êèí‰ª∂Ôºö$(grep "CONFIG_PACKAGE_luci-app-\(.*\)=y" $openwrt_root/.config | sed "s/CONFIG_PACKAGE_luci-app-\(.*\)=y/\1/g" | grep -v "_\|arpbind\|autoreboot\|firewall\|mtk\|opkg\|mtwifi\|ramfree\|package-manager") >> release.txt
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Â∞ÜÂõ∫‰ª∂‰∏ä‰º†Âà∞release
      uses: softprops/action-gh-release@v1
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: upload-release
      with:
        name: ${{ github.workflow }}-${{ env.FIRMWARE_VERSION }}
        tag_name: ${{ github.workflow }}
        body_path: release.txt
        files: ${{ env.FIRMWARE }}/*

    
